# This file is generated by tools/render_homebrew_formula.sh after each release.

class TranslategemmaUi < Formula
  desc "Local TranslateGemma app with CLI, TUI, and embedded Web UI"
  homepage "https://github.com/xzhih/translategemma-ui"
  license "MIT"
  version "0.1.7"

  on_macos do
    on_arm do
      url "https://github.com/xzhih/translategemma-ui/releases/download/v0.1.7/translategemma-ui_0.1.7_darwin_arm64.tar.gz"
      sha256 "733b05e271fce0c63983da1da5345b135b852a1d00226d7650e048030eb9574c"
    end
    on_intel do
      url "https://github.com/xzhih/translategemma-ui/releases/download/v0.1.7/translategemma-ui_0.1.7_darwin_amd64.tar.gz"
      sha256 "7e8f974e30a9e2c8a85a32669f673e763c29a7b699c20d117dd506f021133d1e"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/xzhih/translategemma-ui/releases/download/v0.1.7/translategemma-ui_0.1.7_linux_arm64.tar.gz"
      sha256 "bf2e4f407818ae4eab9e7306fc09f0e58fb22baea09146d741828cf44303d799"
    end
    on_intel do
      url "https://github.com/xzhih/translategemma-ui/releases/download/v0.1.7/translategemma-ui_0.1.7_linux_amd64.tar.gz"
      sha256 "3a4b2b5836c4f292a53f0a9faa7498488255ced16b2065ee0c0786eb355b393e"
    end
  end

  def install
    bin.install "translategemma-ui"
  end

  test do
    assert_match "translategemma-ui version=", shell_output("#{bin}/translategemma-ui --version")
  end
end
