# This file is generated by tools/render_homebrew_formula.sh after each release.

class TranslategemmaUi < Formula
  desc "Local TranslateGemma app with CLI, TUI, and embedded Web UI"
  homepage "https://github.com/xzhih/translategemma-ui"
  license "MIT"
  version "0.0.0"

  on_macos do
    on_arm do
      url "https://github.com/xzhih/translategemma-ui/releases/download/v0.0.0/translategemma-ui_0.0.0_darwin_arm64.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
    on_intel do
      url "https://github.com/xzhih/translategemma-ui/releases/download/v0.0.0/translategemma-ui_0.0.0_darwin_amd64.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/xzhih/translategemma-ui/releases/download/v0.0.0/translategemma-ui_0.0.0_linux_arm64.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
    on_intel do
      url "https://github.com/xzhih/translategemma-ui/releases/download/v0.0.0/translategemma-ui_0.0.0_linux_amd64.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end

  def install
    bin.install "translategemma-ui"
  end

  test do
    assert_match "translategemma-ui version=", shell_output("#{bin}/translategemma-ui --version")
  end
end
