# This file is generated by tools/render_homebrew_formula.sh after each release.

class TranslategemmaUi < Formula
  desc "Local TranslateGemma app with CLI, TUI, and embedded Web UI"
  homepage "https://github.com/xzhih/translategemma-ui"
  license "MIT"
  version "0.1.4"

  on_macos do
    on_arm do
      url "https://github.com/xzhih/translategemma-ui/releases/download/v0.1.4/translategemma-ui_0.1.4_darwin_arm64.tar.gz"
      sha256 "2f56c4a91ba44e9ab34acfc86b2e14da41611b9f57baae83460976f502aea742"
    end
    on_intel do
      url "https://github.com/xzhih/translategemma-ui/releases/download/v0.1.4/translategemma-ui_0.1.4_darwin_amd64.tar.gz"
      sha256 "19aad90ae8d1e5220e1eed8baab2ef80dd4fc56e28e80e3186fc1d543fd36dd4"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/xzhih/translategemma-ui/releases/download/v0.1.4/translategemma-ui_0.1.4_linux_arm64.tar.gz"
      sha256 "c0cd9fa01364c3d9e0adb68221c0cc9c6d19d8bd0b9abea46c0a5a812af1a56a"
    end
    on_intel do
      url "https://github.com/xzhih/translategemma-ui/releases/download/v0.1.4/translategemma-ui_0.1.4_linux_amd64.tar.gz"
      sha256 "58cd1785bd86e0ba5553928b1fc7317592fc708ce8eb3b92b20cc57687123111"
    end
  end

  def install
    bin.install "translategemma-ui"
  end

  test do
    assert_match "translategemma-ui version=", shell_output("#{bin}/translategemma-ui --version")
  end
end
