#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VERSION="${1:-${VERSION:-}}"
CHECKSUM_FILE="${2:-${CHECKSUM_FILE:-}}"
OUTPUT_FILE="${3:-${OUTPUT_FILE:-$ROOT_DIR/Formula/translategemma-ui.rb}}"

if [[ -z "$VERSION" ]]; then
  echo "version is required" >&2
  exit 1
fi

if [[ -z "$CHECKSUM_FILE" ]]; then
  echo "checksum file is required" >&2
  exit 1
fi

if [[ ! -f "$CHECKSUM_FILE" ]]; then
  echo "checksum file not found: $CHECKSUM_FILE" >&2
  exit 1
fi

VERSION_NO_V="${VERSION#v}"
BASE_URL="https://github.com/xzhih/translategemma-ui/releases/download/${VERSION}"

checksum_for() {
  local artifact="$1"
  local checksum
  checksum="$(awk -v artifact="$artifact" '$2 == artifact { print $1 }' "$CHECKSUM_FILE")"
  if [[ -z "$checksum" ]]; then
    echo "missing checksum for ${artifact}" >&2
    exit 1
  fi
  printf '%s' "$checksum"
}

macos_arm_artifact="translategemma-ui_${VERSION_NO_V}_darwin_arm64.tar.gz"
macos_intel_artifact="translategemma-ui_${VERSION_NO_V}_darwin_amd64.tar.gz"
linux_arm_artifact="translategemma-ui_${VERSION_NO_V}_linux_arm64.tar.gz"
linux_intel_artifact="translategemma-ui_${VERSION_NO_V}_linux_amd64.tar.gz"

mkdir -p "$(dirname "$OUTPUT_FILE")"

cat >"$OUTPUT_FILE" <<EOF
# This file is generated by tools/render_homebrew_formula.sh after each release.

class TranslategemmaUi < Formula
  desc "Local TranslateGemma app with CLI, TUI, and embedded Web UI"
  homepage "https://github.com/xzhih/translategemma-ui"
  license "MIT"
  version "${VERSION_NO_V}"

  on_macos do
    on_arm do
      url "${BASE_URL}/${macos_arm_artifact}"
      sha256 "$(checksum_for "$macos_arm_artifact")"
    end
    on_intel do
      url "${BASE_URL}/${macos_intel_artifact}"
      sha256 "$(checksum_for "$macos_intel_artifact")"
    end
  end

  on_linux do
    on_arm do
      url "${BASE_URL}/${linux_arm_artifact}"
      sha256 "$(checksum_for "$linux_arm_artifact")"
    end
    on_intel do
      url "${BASE_URL}/${linux_intel_artifact}"
      sha256 "$(checksum_for "$linux_intel_artifact")"
    end
  end

  def install
    bin.install "translategemma-ui"
  end

  test do
    assert_match "translategemma-ui version=", shell_output("#{bin}/translategemma-ui --version")
  end
end
EOF
